(defun down (start values)
  (when values
    (let* ((current (car values))
           (end (- start (1- (cdr current)))))
      (if (= start end)
          (format t "    ~a <= content(~d);~%" (car current) start)
          (format t "    ~a <= content(~d downto ~d);~%" (car current) start end))
      (down (1- end) (cdr values)))))

(defvar control-commands '(("NA" .  17)
                           ("MS" .  3)
                           ("MC" .  1)
                           ("IL" .  1)
                           ("PI" .  1)
                           ("PL" .  1)
                           ("TD" .  4)
                           ("TA" .  4)
                           ("TB" .  4)
                           ("MB" .  1)
                           ("FS" .  5)
                           ("MD" .  1)
                           ("RW" .  1)
                           ("MM" .  1)
                           ("MW" .  1)
                           ("RV" .  1)
                           ("RC" .  1)
                           ("RN" .  1)
                           ("RZ" .  1)
                           ("FL" .  1)))
